# Generated by Django 3.0.5 on 2020-04-07 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
