# Generated by Django 3.0.5 on 2020-04-07 04:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dj', '0003_auto_20200407_0211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('amount', models.IntegerField(default=0)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj.Image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj.User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
