# Generated by Django 3.0.5 on 2020-04-07 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj', '0004_donation'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='donation',
            table='donation',
        ),
        migrations.AlterModelTable(
            name='image',
            table='image',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
